version: "3.9"
services:
  web: 
    build: ./client
    ports:
      - 3000:3000 
    environment:
      - REACT_APP_API_ENDPOINT=http://localhost:8000
    depends_on:
      - api
  api:
    build: ./server
    ports:
      - 8000:8000